### ISSUE TITLE
Cannot load DLL

### ISSUE THREAD

**Issue by mfread** [JoJoBond/Powershell-YouTube-Upload#1]
Hi JoJoBond.

I have downloaded your package onto my Windows 10 laptop and thrown all the files from the ZIP into C:\Users\xxx\yt. 

I cannot get past the Add-Type DLL ....

`try
{
    write-host "loading google api ...";
    Add-Type -LiteralPath "C:\Users\xxx\yt\Google.Apis.YouTube.v3.Merged.dll";
    write-host "v3 API library loaded";
}
catch
{
    write-host "Failed to load v3 API library";
    $ErrorMessage = $_.Exception.Message;
    $FailedItem = $_.Exception.ItemName;
    write-host "ErrorMessage = $ErrorMessage";
    write-host "FailedItem = $FailedItem";
}`

The error I get is:

`Add-Type : Could not load file or assembly 'file:///C:\users\xxx\yt\Google.Apis.YouTube.v3.Merged.dll' or one of its dependencies. Operation is not supported. (Exception from 
HRESULT: 0x80131515)
At line:1 char:1
+ Add-Type -LiteralPath "Google.Apis.YouTube.v3.Merged.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand`

Is there something else I need to download (dependencies)?  I have .Net 4.5 installed.

Also, what does the **Google.Apis.YouTube.Samples.MyUploads.exe** file do?

Many thanks,
Mark

**Comment by JoJoBond** [comment]
Hi,

this repo is quite old, and I actually don't do it the way it is done (loading the dll into the powershell runtime) in the repo anymore. I will have to update to my new method, that uses a simple .Net executable.

**Comment by instantdreams** [comment]
Reminder to update to your new method!

**Comment by JoJoBond** [comment]
Updated to new method.

**Comment by instantdreams** [comment]
Freaking sweet. You rock.

**Comment by JoJoBond** [comment]
If I happen to have broken some stuff, please open another issue.
