### ISSUE TITLE
Add wiki to create the json file information

### ISSUE THREAD

**Issue by Ventrex** [JoJoBond/Powershell-YouTube-Upload#11]
First of all, nice work with this script!
Sadly I am stuck and am unable to find the solution for this.

is it possible to create a small or step by step wiki where you can find the correct info for the json file?

I think i had the correct info, but a  webbrowser pop ups with 401 OAuth error. 
So I think I made a mistake somewhere.

ow i use the .ps1 file and the .exe and .json are in the same folder

**Comment by JoJoBond** [comment]
In the Credentials page in the API Console you should create a OAuth 2.0-Client-ID. Once created you can view the Client-ID and Client-Key by clicking the downward facing arrow on the right side of the entry. There is also an option to download a JSON file.
When logging in, make sure to select an account that actually has a YouTube channel attached to it. If you want to remove your login, delete the "Google.Apis.Auth" folder in %appdata%.

**Comment by Ventrex** [comment]
Thank you so much!
