### ISSUE TITLE
When i try to upload using this tool youtube blocks the video

### ISSUE THREAD

**Issue by JonathanP91** [JoJoBond/Powershell-YouTube-Upload#14]
Hello,

Youtube puts my video in private + locked when I try to upload using your tools, but when I upload it manually it works fine !
I got the following message : " spam, deceptive practices and scams policy."

I keep it simple and only do this : 
Add-YouTube-Video -File $fullpath -Title $tempTitle -CategoryID 1 -PrivacyStatus 'private'

I can upload the video private, but if I put it on public it goes Private and lock !

Could it be missing attributes ? Like the "is this video for child ?"

I don't know if you can try to reproduce on your side, and sorry for my poor english !

Regards,

**Comment by JoJoBond** [comment]
Try commit 7e01a204dbedcf83d78763eb5f900fcc0cb5623a , that has updated YouTube API library. If that doesn't help IDK what to do. I gave up on using the YouTube API long time ago, I don't plan on going back to it.

**Comment by JonathanP91** [comment]
![image](https://github.com/JoJoBond/Powershell-YouTube-Upload/assets/43779400/86d4152d-a400-40d3-90a9-634543df3c5a)
nope same issue, thank you for your fast answer !

Could be related to the category i used, i will see, could you tell me which DLL were used in the .exe so I could be autonomous in powershell to upload a video ?

**Comment by JoJoBond** [comment]
It's just the YouTube API nuGet package plus dependencies: https://www.nuget.org/packages/Google.Apis.YouTube.v3

**Comment by JonathanP91** [comment]
Thank you, and from what I see the api account needs to be verified, but theyr website is not working to be verified xD, ridiculous
