### ISSUE TITLE
Error with $p.StandardOutput.Peek()

### ISSUE THREAD

**Issue by instantdreams** [JoJoBond/Powershell-YouTube-Upload#2]
**Steps to Reproduce**
1. Clone repository to D:\[...]\Scripts\Powershell-YouTube-Upload
2. Set up clientsecrets.json file using Google Developer center
3. Use the following commands:
```
D:
cd \[...]\Scripts\Powershell-YouTube-Upload
Import-Module .\YouTube.ps1
Add-YouTube-Video -File "[filename.mp4]" -Title "[title]" -CategoryID 22 -Description "[description]" -PrivacyStatus "unlisted" -LocationDescription "[location]" -RecordingDate "2019-05-24"
```

**Problem**
The following error message appeared and would loop without end until killed with CTRL+C:
```
You cannot call a method on a null-valued expression.
At D:\[...]\Scripts\Powershell-YouTube-Upload\YouTube.ps1:194 char:17
+             if ($p.StandardOutput.Peek())
+                 ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
This appears to be from the object $p which is instantiated at line 185.

**Comment by JoJoBond** [comment]
Can you check if https://github.com/JoJoBond/Powershell-YouTube-Upload/commit/4fd61df55d43be0a6d9efd0e6ab0ce8c2e4b7263 fixed it for you?

**Comment by instantdreams** [comment]
That fixed the issue. Now I'm testing.

**Comment by instantdreams** [comment]
Testing worked, reporting success, can be closed

**Comment by JoJoBond** [comment]
Perfect. If you find any more bugs just open a new issue. Cheers!
