### ISSUE TITLE
LocationDescription is not wrapped with escaped quotes

### ISSUE THREAD

**Issue by instantdreams** [JoJoBond/Powershell-YouTube-Upload#3]
Location is provided to the script in the format "location, region". The script sets the parameter as:
```145        $YouTubeCLI_Params += " -LocationDescription $LocationDescription";```
This should be:
```145        $YouTubeCLI_Params += " -LocationDescription `"$LocationDescription`"";```

**Comment by JoJoBond** [comment]
Please check comit https://github.com/JoJoBond/Powershell-YouTube-Upload/commit/3c25bc1530ea653eda95727eb9dc8d39454a8148

**Comment by instantdreams** [comment]
Commit pulled and tested, Issue with $LocationDescription appears to be resolved.

**Comment by JoJoBond** [comment]
Thanks! Closing.
