### ISSUE TITLE
Authentication Loop

### ISSUE THREAD

**Issue by instantdreams** [JoJoBond/Powershell-YouTube-Upload#4]
Prerequisites:
1. Create ```client_secrets.json```
2. Place in scripts folder ```..\Scripts\Powershell-YouTube-Upload```

Steps to reproduce:
1. Open PowerShell window
2. Enter the following commands:
```
Set-Location ..\Scripts\Powershell-YouTube-Upload
. .\YouTube.ps1
Add-YouTube-Video -File "location\filename.mp4" -Title "title" -CategoryID 22 -Description "description" -PrivacyStatus "unlisted" -LocationDescription "location, area" -RecordingDate 2019-05-05
```

Result:
1. Code starts with no errors
2. Google OAuth web page is displayed to request an account
3. Account is selected
4. Permissions are granted to "Manage your YouTube videos"
5. Permissions are granted to "Manage your YouTube account"
6. Choices are confirmed and allowed
7. Token received: "Received verification code. You may now close this window. "
8. The same OAuth web page is diplayed
9. The same authentication process can be repeated multiple times

Status:
1. Closing the OAuth web page leave the script waiting

**Comment by JoJoBond** [comment]
Can you check in the folder "%AppData%\Google.Apis.Auth" if there is a file named "Google.Apis.Auth.OAuth2.Responses.TokenResponse-user"? If so, please delete this file and retry. Check if the file being created after oauth verification.

**Comment by instantdreams** [comment]
File folder "%AppData%\Google.Apis.Auth" is empty.
________________________________

**Comment by JoJoBond** [comment]
Weird. I will have to look into this. Please check if the executing user has read/write access to that folder. The O-Auth implementation is taken 1:1 from google Code Samples (https://developers.google.com/youtube/v3/code_samples/dotnet#upload_a_video) so I don't think that the issue is there. I'm quite busy over the next day, but I hope that I will find some time on Friday to dig deeper.

**Comment by JoJoBond** [comment]
Sorry, but I can't reproduce the issue. Could you provide the following data for me to narrow it down?
- OS: Version, Edition, Bitness, Buildversion/Servicepack
- Default browser
- UAC status (slider position, or disabled in registry)
- Are there gmail-addresses and youtube-channels linked to your google account (at the same time)?

**Comment by instantdreams** [comment]
Testing will be redone after a re-clone of solution and refresh of `client_secrets.json`. Results tomorrow, but for reference:

* OS: Windows Server 2017 Essentials 1607.14393.3025
* Browser: Firefox Quantum 67.0.2
* UAC Status: Notify me only when apps try to make changes
* Gmail Status: 1 Gmail address 1 YouTube channel

Script is called by another script.

**Comment by instantdreams** [comment]
Well, Google rejected my attempt to verify my API, but after attempting again this morning and overriding the authorisation request everything seemed to work for 6 videos, the last two gave Max Retry error messages. So that's good at least.
