### ISSUE TITLE
Unable to find type System.Drawing.PointF

### ISSUE THREAD

**Issue by instantdreams** [JoJoBond/Powershell-YouTube-Upload#5]
I am calling the script from my own script and I get the following error:
```
Unable to find type [System.Drawing.PointF].
At D:\Scripts\Powershell-YouTube-Upload\YouTube.ps1:92 char:9
+         [System.Drawing.PointF]$LocationCoordinates,
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Drawing.PointF:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```
I am calling my script using `-ExecutionPolicy Bypass -NoLogo -NonInteractive` - so it looks like you'll have to load this assembly explicitly to support calls from scripts.

**Comment by JoJoBond** [comment]
Please use the latest version from the master branch. I switched these types in commit 14a392278fd7dbce11acf85447203d4648adbdda

**Comment by instantdreams** [comment]
Latest version cloned and `client_secrets.json` refreshed. Will confirm results after scheduled run at 06:00 18-Jun-2019.

**Comment by instantdreams** [comment]
Pull for latest fixed this. My bad.
