### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by brunoinds** [JoJoBond/Powershell-YouTube-Upload#6]
Please, explain how to start the CLI?

**Comment by JoJoBond** [comment]
The CLI is wrapped via the powershell script. If you are eager to use it manually check the Main.cs in the sources. There you'll find an enum called FSM_ArgParser. The possible options are defined in there. Options have to start with a minus and are directly followed by the name. After that comes a blank and the value for that option.  E.g. `-Mode Video` or `-Operation Add`. For a simple video upload you can try: `YoutubeCLI.exe -Mode Video -Operation Add -Title "test upload" -CategoryID 1 -File "c:\example.mp4"`.
