### ISSUE TITLE
Add Video to playlist?

### ISSUE THREAD

**Issue by ulfwuestefeld** [JoJoBond/Powershell-YouTube-Upload#8]
Is there any function to add uploaded videos to a playlist?

**Comment by JoJoBond** [comment]
You mean appending new videos to an existing playlist? That's not possible right now. I can look into it.

**Comment by ulfwuestefeld** [comment]
Exactly.
That would be fine.

**Comment by ulfwuestefeld** [comment]
Currently i'm working on a kind of bulk uploader based on your youtubecli to upload my videos to youtube without getting in trouble with the quota. And the the videos shall be listed in the same playlist.

**Comment by JoJoBond** [comment]
Please checkout commit 5ae2b8e63f93224b394245a2643471e15d627faa and try the new Include/Exclude from playlist functions. I have not tested these, so please report any problems you may encounter.

**Comment by ulfwuestefeld** [comment]
Thanks. I'll try it as soon as my exceeded quota will let me.

**Comment by ulfwuestefeld** [comment]
Wow, that is really cool stuff. Thanks for implementing it. Adding (including) video to a existing playlist works like a charm!
